### ISSUE TITLE
Can it run on multiple words in wild ?

### ISSUE THREAD

**Issue by Sukanya-Kudi** [gasparian/CRNN_OCR_lite#4]
Hi,

I am trying to execute the code on my custom data which are handwritten images in the wild. 
python predict.py --G 0 --model_path ./models\OCR_mjsynth_FULL_2 --image_path ./imgs/pages/ --result_path ./
 Do we require the image to be constraint to one word ?

**Comment by gasparian** [comment]
Hi, @Sukanya-Kudi !
Yes, you're right. It because all models have been trained on single words and it's actually hard to get rather good performance on "sentence-level"...
So, as I said in the readme, OCR itself must be applied after word-detector (see [EAST](https://github.com/kurapan/EAST) or [TextBoxes++](https://github.com/mvoelk/ssd_detectors) as reference).

**Comment by Sukanya-Kudi** [comment]
Thank You for your inputs.
